### ISSUE TITLE
Litet språkfel

### ISSUE THREAD

**Issue by PierreMesure** [zetkin/zetkin.org#61]
Hej Richard,

Hittade ett litet fel i en text och försökte skicka en PR men det ser ut som att webbplatsen inte speglar källkoden. Eller har jag missat den relevanta filen (tänkte det skulle vara [där](https://github.com/zetkin/zetkin.org/blob/40dcd4fb33bb3ff44523884544b428a5866ae707/en/join.md?plain=1#L7))?

Felet är här:

<img width="648" alt="image" src="https://user-images.githubusercontent.com/7223028/163318253-2590e7f9-8f31-4c8f-9f6f-03f5e3018540.png">

**Comment by richardolsson** [comment]
Thanks for pointing that out! I believe what you're looking for is this: 😊 

https://github.com/zetkin/zetkin.org/blob/40dcd4fb33bb3ff44523884544b428a5866ae707/_data/strings/en.yml#L43-L47

If you want to create a PR that would be great!

**Comment by PierreMesure** [comment]
Ah great! I did a text search in the whole repo but somehow missed this file! The PR is sent!
